# Generated by Django 5.1.1 on 2024-10-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='manufacturer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='name',
        ),
    ]
